- hosts: client
  gather_facts: yes
  tags: client
  vars_files:
   - vars/main.yml
  tasks:

   - name: copy consul zip file
     copy: src=files/{{ consul_pkg }} dest={{ consul_temp }}
     register: consul_copy

   - name: copy consul zip file
     command: echo "consul copy failed"
     when: consul_copy | failed

   - name: unarchive consul
     unarchive: src={{ consul_temp }}/{{ consul_pkg }} dest={{ consul_bin_path }} copy=no
     register: unarchive_consul
     when: consul_copy | success

   - name: Create client  directory
     file: path={{ consul_client_dir }} state=directory
     when: unarchive_consul | success

   - name: Create script directory
     file: path={{ consul_scritp_dir }} state=directory
     when: unarchive_consul | success

   - name: copy script to script directory
     copy: src=files/scripts/  dest={{ consul_scritp_dir }} mode=0777
     when: unarchive_consul | success

   - name: copy client template
     template: src=templates/client.j2  dest={{ consul_client_dir }}/config.json
     when: unarchive_consul | success

   - name: consul boot scritp
     template: src=templates/consul-client.j2  dest=/etc/init/consul.conf
     when: unarchive_consul | success

   - name: Allowing 8301 port in client nodes
     command: iptables -I INPUT 1 -s {{ client_ip_range }} -p tcp -m tcp --dport 8301 -j ACCEPT

   - name: start consul server
     command: start consul
